<template><div><h1 id="錾制元素法典" tabindex="-1"><a class="header-anchor" href="#錾制元素法典" aria-hidden="true">#</a> 錾制元素法典</h1>
<h2 id="说明" tabindex="-1"><a class="header-anchor" href="#说明" aria-hidden="true">#</a> 说明</h2>
<p><code v-pre>Civitai&amp;社区图片常用/好用二次元parameters合集。</code></p>
<p><code v-pre>本文中所有资料任何权益不属于整理者本人，形式上借鉴《元素法典》</code></p>
<ul>
<li><strong>除内容本身外，最终解释权归 錾制千秋yuno779 所有</strong></li>
<li><strong>合集内容为二次元相关tag串合集，最好使用二次元模型而非3D</strong></li>
<li><strong>大部分示例图为KawaICE模型生成:</strong><a href="https://civitai.com/models/51057/" target="_blank" rel="noopener noreferrer"><strong>https://civitai.com/models/51057/</strong><ExternalLinkIcon/></a></li>
<li><strong>本tag集会持续整理，详情链接：<a href="https://civitai.com/models/62473" target="_blank" rel="noopener noreferrer">https://civitai.com/models/62473<ExternalLinkIcon/></a></strong></li>
<li><strong>本parameters集不含有NSFW内容</strong></li>
<li><strong>由于存在不良商家拿着本文去坑其小白的钱，故限制合集转载：</strong></li>
<li><strong>《CIVITAI法典》第一发布链接：<a href="https://civitai.com/models/62473" target="_blank" rel="noopener noreferrer">https://civitai.com/models/62473<ExternalLinkIcon/></a></strong></li>
<li><strong>其余均为转载，[允许任何不含盈利行为的转载]</strong></li>
<li><strong>禁止任何形式以此获取收益，遇到不良商家请直接举报！</strong></li>
</ul>
<p><strong>在AI模型高速发展的现在，parameters似乎已经没有多少人在研究了，很多人就只会1girl等类似tag进行抽卡。有很多有能力写tag串的人，也慢慢的开始不再分享自己的tag串。当在交流平台问到一些图的parameters时，要么就是“1girl”这种非常简单的抽卡tag，要么就会有人说：“这是XXX的tag，你自己问他去”/“tag作者不愿意分享”。</strong></p>
<p><strong>这在早期《元素法典》的限制下并不存在的问题，随着《元素法典》的停更慢慢的开始暴露出来了。甚至有一部分人拿着自己的“宝贝”tag串，在一些绘画的平台出售自己“高贵”的AI生成作品。所以，《錾制元素法典》意在破除这一现象，除了在Civitai模型分享站以外，法典编辑组也会在各AI绘画相关社区/群聊，来收集相关parameters（tag串），同时也会接受来自社区的投稿。基本要求是:</strong></p>
<p>【1】 二次元图片/模型相关，包含2.5D。</p>
<p>【2】 能够在较多数模型里使用，最起码不能是只有几个模型能用。</p>
<p>【3】 投稿方式为直接在<a href="https://civitai.com/models/62473" target="_blank" rel="noopener noreferrer">这里<ExternalLinkIcon/></a>下方图片评论区发布带有生成信息的图片即可投稿</p>
<h2 id="使用方法" tabindex="-1"><a class="header-anchor" href="#使用方法" aria-hidden="true">#</a> 使用方法</h2>
<table>
<thead>
<tr>
<th>↓↓</th>
</tr>
</thead>
<tbody>
<tr>
<td><strong>第一步：从文档复制提示词</strong> <strong>Copy the parameters from the document</strong> <img src="@source/posts/media/6ecd903e7167a3899fcf28e75999d612.png" alt="" loading="lazy"> <strong>第二步：直接粘贴到正面提示词那一栏</strong> <strong>Direct paste</strong> <img src="@source/posts/media/88fb488eb1fde1b2eb70a1a5d1e9cc26.png" alt="" loading="lazy"> <strong>第三步：点击右侧的箭头，一键导入生成信息</strong> <strong>Click the arrow on the right to import parameters with one click</strong> <img src="@source/posts/media/874fc5e82d9334076d6b1de0f77f662e.png" alt="" loading="lazy"> <strong>第四步：根据自己情况调整下面的参数，记得点一下随机种子</strong> <strong>Adjust the following parameters according to your situation, remember to click on the random seed</strong> <strong><img src="@source/posts/media/5142afe06276942315c63dd449199380.png" alt="FF0XFA5CTQJ@159UWLIWP" loading="lazy"></strong></td>
</tr>
</tbody>
</table>
<h2 id="提示词" tabindex="-1"><a class="header-anchor" href="#提示词" aria-hidden="true">#</a> 提示词</h2>
<figure><img src="@source/posts/media/0e9eb75d38b5fd7e09924f862c33b50e.png" alt="IMG_start" tabindex="0" loading="lazy"><figcaption>IMG_start</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>original, (masterpiece), (illustration), (extremely fine and beautiful), perfect detailed, photorealistic, (beautiful and clear background:1.25), (depth of field:0.7), (1 cute girl with (cat ear and cat tail:1.2) stands in the garden:1.1), (cute:1.35), (detailed beautiful eyes:1.3), (beautiful face:1.3), casual, silver hair, silver ear, (blue hair:0.8), (blue ear:0.8), long hair, coat, short skirt, hair blowing with the wind, (blue eye:1.2), flowers, (little girl:0.65), butterflys flying around Negative prompt: EasyNegative,extra limbs,three leg,three hand,penis Steps: 20, Sampler: DPM++ SDE Karras, CFG scale: 6, Seed: 2068707324, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/0c40f2e8e217d019f34046febd94a7b0.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, blue bow, animal ears, red eyes, long hair, very long hair, long sleeves, solo, bow, hair between eyes, tail, fox tail, bangs, dress, white legwear, white hair Negative prompt: ((cowboy)),(((pubic))), ((((pubic_hair))))sketch, duplicate, ugly, huge eyes, text, logo, monochrome, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), crown braid, ((2girl)), (deformed fingers:1.2), (long fingers:1.2),succubus wings,horn,succubus horn,succubus hairstyle, (bad-artist-anime), bad-artist, bad hand Steps: 20, Sampler: Euler a, CFG scale: 4.5, Seed: 1676232808, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/50284da943ce4a8fb4e721438cbf4211.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality),a girl, solo, twintails, shirt, skirt, petals, bowtie, earrings, jewelry, bangs, black hair, hair ornament, hair ribbon, red ribbon, red eyes, long hair, open mouth, white shirt, multicolored hair, black skirt, red hair, long sleeves, pink bowtie, hair between eyes, looking at viewer, collared shirt, upper body, hand up, falling petals, depth of field, strong bloom, red background Negative prompt: EasyNegative, (worst quality, low quality, normal quality:1.4), lowres, skin spots, acnes, skin blemishes, age spot, glans,extra fingers, fewer fingers,strange fingers,((bad hand)),Hand grip,(lean),Extra ears,(Four ears),Strange eyes,(three arms),Many hands,(Many arms),((watermarking)), Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2314963433, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/880f0f2318a064939de23ed67a882dd3.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>((masterpiece, best quality)),a girl, solo, skirt, sky, sitting, pantyhose, serafuku, cloud,black gloves, outdoors, neckerchief ,day, bangs, fence, shirt, ahoge, rooftop, long hair, white pantyhose, black hair, school uniform, white sailor collar, red eyes, sailor collar, blue skirt, red neckerchief, blue serafuku, animal ears, blue sky, long sleeves, blue shirt, looking at viewer, closed mouth,cat ears, chain-link fence, pleated skirt, cloudy sky, trash can Negative prompt: EasyNegative, (worst quality, low quality, normal quality:1.4), lowres, skin spots, acnes, skin blemishes, age spot, glans,extra fingers, fewer fingers,strange fingers,((bad hand)),Hand grip,(lean),Extra ears,(Four ears),Strange eyes,(three arms),Many hands,(Many arms),((watermarking)), Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3949698018, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/9f0d17646a7031db8733a81e1c5d90f2.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality), 1girl, flower, solo, dress, holding, sky, cloud, hat, outdoors, bangs, bouquet, rose, expressionless, blush, pink hair, flower field, red flower, pink eyes, white dress, looking at viewer, midium hair, holding flower, small breasts, red rose, holding bouquet, sun hat, white headwear, depth of field, Negative prompt: EasyNegative, (worst quality, low quality, normal quality:1.4), lowres, skin spots, acnes, skin blemishes, age spot, glans,extra fingers, fewer fingers,strange fingers,((bad hand)),Hand grip,(lean),Extra ears,(Four ears),Strange eyes,(three arms),Many hands,(Many arms),((watermarking)), Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 539370415, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/5d32103c31cff51534a8600a67a8c572.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>((masterpiece)), expressionless, (((best quality))), ((illustration)), 1girl, elf, ((solo)), (detailed face), (beautiful detailed eyes), light eyes, blue eyes, ((disheveled hair)), silver hair, full body, smile, blank stare, sitting, ((looking to the side)), bow tie hair band, white transparent long skirt, noble, mysterious, bright background, in forest, nature, sunshines through the leaves, butterfly, river, close-up, Negative prompt: EasyNegative, (worst quality, low quality, normal quality:1.4), lowres, skin spots, acnes, skin blemishes, age spot, glans,extra fingers, fewer fingers,strange fingers,((bad hand)),Hand grip,(lean),Extra ears,(Four ears),Strange eyes,(three arms),Many hands,(Many arms),((watermarking)), Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2170027668, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/0ae467263a6990de65176a2d7ba70be5.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(anime screencap style), 1girl, solo, sharp focus, absurdres, best quality, long hair, bangs, blunt bangs, light brown hair, relaxing, outdoors, sunflower field, cute, innocent, virtual youtuber, white dress, x hair ornament, striped thighhigh, single thighhigh, open jacket, yellow eyes, hair ribbon, looking at viewer, puffy long sleeves, green jacket, small breasts, collarbone, criss-cross halter, black choker Negative prompt: easynegative, (worst quality:1.2), (low quality:1.2), (lowres:1.1), (monochrome:1.1), (greyscale:1.1), multiple fingers, fewer fingers, (bad hands, missing fingers:1.25) Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 7.5, Seed: 378389555, Size: 612x849, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/124dcfdc30bb6cc2e627481a6bed74c5.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>best quality:1.4, (loli:1.2), very long eyes, very huge eyes, very small height, very innocent face, white hair, (low twintails:1.4), (very long low twintails), pink eyes, smile, rabbit ears, (playboy bunny), jacket, heels, pantyhose, 1girl, Negative prompt: EasyNegative, bad_prompt_version2, (worst quality:1.4), (low quality:1.4), (trembling:1.2), (animal ears:1.5), furry, (nipples slip:1.4), (text:1.5), 3legs, 3arms, horns, elf ears, mole, borderbox, Steps: 80, Sampler: DPM++ SDE Karras Steps: 28, Sampler: Euler a, CFG scale: 7, Seed: 1447217334, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/303985b79cb7d0894e9e6a48cf1cdd84.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, hair ornament, clover, bow, twintails, smile, stuffed toy, green bow, solo, clover hair ornament, long hair, four-leaf clover, stuffed animal, green nails, black hair, hairclip, shirt, skirt, low twintails, doughnut, bangs, collared shirt, white shirt, stuffed bunny, plaid, long sleeves, food, bowtie, looking at viewer, pink bow, four-leaf clover hair ornament, hair bow, nail polish, sweater, blush, pink eyes Negative prompt: (worst quality, low quality, extra digits:1.4),EasyNegative,male Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1897618263, Size: 768x1152, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/27b44cf68a46f977eef3418f4933bb96.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>mayoi shigure, 1girl, breasts, looking at viewer, blush, smile, short hair, open mouth, bangs, hair ornament, animal ears, hair between eyes, medium breasts, purple eyes, hairclip, pink eyes, crossed bangs, light green hair, weasel ears, gloves, fur trim, gray jacket, gray headwear, animal tail Negative prompt: (worst quality, low quality:1.4), extra fingers, fewer fingers, watermark, EasyNegative, bad_prompt_version2 Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 305891596, Size: 512x768, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/f63801cab876f2bd8123eb8d65d18582.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>illustration, red eyes, black hair, cat ears, hair flower, lotus, wariza, from above, highres, solo focus,, masterpiece, best quality, Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, EasyNegative Steps: 22, Sampler: Euler a, CFG scale: 7.5, Seed: 3141631537, Size: 512x768, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/851e6239710ed375628ce4dc0148da6e.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(Highest picture quality), (Master's work), (ultra-detailed), masterpiece,best quality,absurdres,original,extremely delicate and beautiful,beautiful detailed eyes and face, feet, 1girl, pantyhose, hat, breasts, beret, long_hair, soles, thighband_pantyhose, solo, sitting,small breasts,loli, skirt, no_shoes, jacket, off_shoulder, cleavage, black_headwear, red_eyes, looking_at_viewer, toes, shirt,+ +,light smile, closed mouth, Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry Steps: 25, Sampler: Euler a, CFG scale: 7, Seed: 1475880126, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/c30ebc755075b857ca85cd3c108114ac.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece,((best quality)),(extremely detailed CG unity 8k wallpaper), 1girl,highres, animal_ears, tail,hair_ornament, blue_eyes,long_hair,small_breasts, open_mouth, blush, looking_at_viewer, bare_shoulder, bare belly,smile, solo ,long_hair, eyebrows_visible_through_hair, hair_between_eyes, dress,jacket,legwear Negative prompt: Bad face,owres,worst quality,low quality,normal quality,((blurry)),error,((simple background)),overexposure,ugly,((unnatural body)),((bad anatomy)),(twisted limbs:1.33),(twisted legs),(fused hand:1.33),fused arm,fused thigh,fused calf,fused feet,((extra legs)),three legs,((extra crus)),three crus,extra feet,(bad hands),bad arms,(bad legs),bad feet,(missing fingers),(missing arms),missing legs,(poorly drawn face:1.33),bad face,fused face,cloned face,text,jpeg artifacts,signature,watermark,username Steps: 30, Sampler: DDIM, CFG scale: 7.5, Seed: 2060498502, Size: 576x768, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/85e1a9d95548002471ebeab57595aca0.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece,(best quality),(1girl) ,solo,(high contrast:1.2),(high saturation:1.2), ((hands on the pocket)),((black and white sdress)),looking at viewer,((white and light blue theme:1.3)),((white and light blue background:1.5)),white hair,blue eyes,((walking:1.3)),full body,black footwear,((the light blue water on sky and white cloud and day)),((from above:1.2)), Negative prompt: ((very long hair:1.3)),messy,ocean,beach,big breast,nsfw,(((pubic))), ((((pubic_hair)))),sketch, duplicate, ugly, huge eyes, text, logo, monochrome, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), crown braid, ((2girl)), (deformed fingers:1.2), (long fingers:1.2),succubus wings,horn,succubus horn,succubus hairstyle, (bad-artist-anime), bad-artist, badhandv4, Steps: 47, Sampler: Euler a, CFG scale: 7, Seed: 2478650823, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/9c0c017e9819f05c8beaaefc1ff9dc52.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece,(best quality),(1girl) ,solo,(high contrast:1.2),(high saturation:1.2), ((hands on the pocket)),((black and white sdress)),looking at viewer,((purple and blue theme:1.3)),((purple and blue background:1.5)),white hair,blue eyes,((walking:1.3)),full body,black footwear,((the blue water on ground reflecting the starry sky and nebula and galaxy)),((from above:1.2)) Negative prompt: ((very long hair:1.3)),messy,ocean,beach,big breast,nsfw,(((pubic))), ((((pubic_hair)))),sketch, duplicate, ugly, huge eyes, text, logo, monochrome, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), crown braid, ((2girl)), (deformed fingers:1.2), (long fingers:1.2),succubus wings,horn,succubus horn,succubus hairstyle, (bad-artist-anime), bad-artist, bad hand Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1350098417, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/edb6dc5ba55a2156e801eb452ee9dabd.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece), (best quality), (highly detailed), 1girl, solo, red eyes, holding, disposable cup, looking at viewer, holding cup, outdoors, snow, long sleeves, bangs, cup, coffee cup, tree, closed mouth, bare tree, fur trim, hair between eyes, ribbon, open clothes, bag, winter, black ribbon, snowing, grey hair, coat, hair ribbon, hair bun, upper body, jacket, sidelocks, blush, fur collar Negative prompt: (worst quality, low quality:1.4) Steps: 64, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 2652174113, Size: 768x1152, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/9d9e67bbebacb0f325841e8b943ec248.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(Highest picture quality), (Master's work),(Detailed eyes description),(Detailed face description), 1girl,red eyes,white hair,(very long hair),very long hair (floating in the wind),hair ornament,white dress,small breast,bare legs,white socks,leather shoes,arms and hands behind back,blush,fluttering grass,(spring,sakura blossoms),petals,(lens flare),altocumulus,dazzling light,cool breeze,(shade) of [a sakura tree],meadow,(the grass is growing and the birds are flying),(lake,surface reflection) Negative prompt: nsfw,EasyNegative,nsfw,(low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2),bad composition, inaccurate eyes, extra digit,fewer digits,(extra arms:1.2),2girl,lanjiao5,(feet),shoe,text Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 8, Seed: 3526151994, Size: 512x768, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/b11c8e5edb7e7b362e783d9984e0c93c.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>englai Fairyland,Chinese mythology,Colorful auspicious clouds, autumn, autumn_leaves, falling_leaves, holding_leaf, leaf, leaf_background, leaf_hair_ornament, maple_leaf, aki_shizuha, leaf_print, starfish, anger_vein, ginkgo_leaf, leaf_on_head, spoken_anger_vein, tree, waterfall, sweet_potato, dragonfly, acorn, solo, braid, blurry_foreground, 1girl, day, painting, depth_of_field, blurry, long_hair, branch, hair_ornament, leaves_in_wind, forest, outdoors, nature, campfire, shirt, looking_at_viewer, onsen, koi, sitting, masterpiece, best quality, (best quality), ((masterpiece)), (highres), original, extremely detailed 8K wallpaper, (an extremely delicate and beautiful),((detailed face)),beautiful detail eyes,hair fluttering in the wind,messy hair,lens flare, 1girl,full body,(golden eye),(red eye),(wolf ear),(yellow hair),(wolf tail),(wolf ears),(a cute young girl:1.1),(wolf ear),beautiful detailed eyes,orange hair, very long hair,small breasts,(looking at viewer), Negative prompt: nsfw,EasyNegative,nsfw,(low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2),bad composition, inaccurate eyes, extra digit,fewer digits,(extra arms:1.2),2girl,text Steps: 47, Sampler: DPM++ 2M Karras, CFG scale: 8, Seed: 3889282593, Size: 512x768, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/5cb80b998e7f175f65df4b2a68b3881e.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece,best quality:1.5), 1girl, solo, solo focus, (animal ears, rabbit ears), barefoot, knees up, dress, sitting, short sleeves, looking at viewer, grass, short hair, smile, white hair, puffy sleeves, outdoors, puffy short sleeves, bangs, on ground, full body, animal, sunlight, brown eyes, dappled sunlight, day, depth of field, open mouth, (flower, hair flower), w, wariza, white dress, Negative prompt: EasyNegative, fewer digits, nude, extra digits, extra ears, (bad hands) Steps: 24, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1867465867, Size: 512x768, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/c04dd37250ec0796304b566864f8d99d.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, ;d, blue dress,lurry background, choker, cloud, collarbone, dekalco, depth of field,hair between eyes, long hair, looking at viewer, one eye closed, open mouth, outdoors, puffy short sleeves, puffy sleeves, red bag, ribbon-trimmed choker, short sleeves, sky, smile, soft serve, solo, upper body, yellow eyes, red hair,night, arms behind back, lantern, \&lt;lora:kitaIkuyoBocchiTheRock_v10a:0.7\> Negative prompt: easynegative Steps: 28, Sampler: DPM++ 2M Karras, CFG scale: 6, Seed: 1817664267, Size: 512x768, Model hash: a16480e64f, Model: [Merge]loli1-fix, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/48c4f6ef5ab9e0b6af15bd5ff243b4d9.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>bat, candy, halloween, halloween_bucket, halloween_costume, happy_halloween, jack-o'-lantern, pumpkin, pumpkin_hair_ornament, pumpkin_hat, tattoo, trick_or_treat, witch_hat, body_writing, pubic_tattoo, tombstone, garter_straps,pasties, thighhighs, silk, ghost_costume, lollipop, spider_web, 1girl, vampire_costume, bat_hair_ornament, basketball, food-themed_hair_ornament, graveyard, long_hair, orange_ribbon, heart_tattoo, holding_vegetable, broom, candy_cane, orange_choker, bat_wings, basket, small breasts, solo, candle, food, orange_bow, open_mouth, bat_print, castle, orange_panties, black_legwear,vegetable, bow, shoulder_tattoo, orange_nails, gloves, twintails, spider_web_print, blonde_hair, very_long_hair, lantern, grave, charmander, orange_legwear, navel, bare_tree, smile, orange_bowtie, elbow_gloves, cookie, full_moon, cape, mini_witch_hat, bridal_gauntlets Negative prompt: nsfw,EasyNegative,nsfw,(low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2),bad composition, inaccurate eyes, extra digit,fewer digits,(extra arms:1.2),2girl,text Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 8, Seed: 2268575219, Size: 512x768, Model hash: f74bd538e4, Model: KawaICE_FP16, Denoising strength: 0.7, Clip skip: 2, ENSD: 31337, Hires upscale: 2, Hires steps: 10, Hires upscaler: R-ESRGAN 4x+ Anime6B, AntiBurn: Count=3;
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/f604b6fa10ecd023812a4ad326df920d.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece, best_quality,1girl, solo,fox_ears,yellow eyes:1.5\|green eyes:1.1,(pink hair:1.2\|blonde hair), gentle hazel eyes, flowing wavy hair, ankle socks, gazing at viewer, white socks, ballet flats, pastel sundress, full body, butterfly garden, surrounded by fluttering butterflies, sunlight filtering through leaves, serene expression, spring Negative prompt: nsfw,EasyNegative,nsfw,(low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2),bad composition, inaccurate eyes, extra digit,fewer digits,(extra arms:1.2),2girl,lanjiao5,text Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 8, Seed: 1560516400, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/c5b047c6ee60e96b77a254ce7d1960df.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, bright purple hair, orange streaked hair, colored inner hair, (cat ears:1.1), bare neck, bare shoulders, purple dress, orange and purple eyes, gradient eyes, collarbone, cowboy shot, solo, head tilt, laughing, (smile:0.8), detailed background, crazy eyes, fang, cat girl, outdoors, sunset, BREAK, chiaroscuro, skin caustics, volumetric lighting, rim light, key light, fill light, light particles, exceptional, masterpiece, extremely detailed, Negative prompt: (fox ears:1.1), (fox girl:1.1), (EasyNegative:0.7), loli, child, simple5.5, simple5.6 Steps: 16, Sampler: Euler a, CFG scale: 6.6, Seed: 2669183668, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337, Discard penultimate sigma: True
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/19b0e67961708b4a6be8c97d0f33b672.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>original character , beautiful girl with green wavy hair , witch hat , sitting in a dimley lit room , candles , casting a spell , sitting on the floor , dark room , reading a spell book, looking away , shallow depth of field , rendered , stunning details Negative prompt: (Worst Quality, Low Quality:1.4), Poorly Made Bad 3D, Lousy Bad Realistic , bad hands , tangled fingers , extra fingers Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2722568367, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/35ce7bacafde8e68c1e2f884d1a7db95.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece, best quality, 1girl, solo, long_hair, looking_at_viewer, white hair, red eyes, smile, bangs, skirt, shirt, long_sleeves, hat, dress, bow, holding, closed_mouth, flower, frills, hair_flower, petals, bouquet, holding_flower, center_frills, bonnet, holding_bouquet, flower field, flower field, colorful, vivid color, blue sky, lens flare, depth of field, dutch angle Negative prompt: EasyNegative, badhandv4 Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3900605018, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/966302691c4902db3087e0af0f14d892.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>((masterpiece:1.4, best quality))+, (ultra detailed)+, (detailed screen UI design:1.4),1girl,cute girl doing live streaming,(detailed layout)+, including elements such as chat box, side bar, (icon),She's in the sidebar of the screen,silver hair,pale-blonde long twintails, violet eyes, cyberpunk,,(white thighhighs), cute girl,blue clothes,(flat chest:1.3), (english text:1.25), Negative prompt: (nsfw), (worst quality, low quality:1.4), (Easynegative:1.2),(bad anatomy), (inaccurate limb:1.2),poorly eyes, extra digit,fewer digits,six fingers,(extra arms,extra legs:1.2),(realistic),(real life),oldest,old,bad aesthetic,normal aesthetic,worst quality, low quality, normal quality,lowres, bad anatomy,(blurry),re-badprompt,(badhandv4),(big chest:1.4),(multiple people), Steps: 20, Sampler: Euler a, CFG scale: 5, Seed: 784888369, Size: 1216x576, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/e0e5ec9530309d4973a6b2bc39acfcab.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>extremely detailed CG unity 8k wallpaper, masterpiece, best quality, ultra-detailed, an extremely delicate and beautiful, night, dark, dim candlelight, candle, messy study room, many books, grimoire, book stock, magic girl, sleepy, head rest, black robe, vase, finely detail,, masterpiece, best quality, Negative prompt: lowers,(worst quality, low quality:1.4),(bad hands, bad finger, bad fingers:1.2), (sfw:1.05),(artist name:1.1), (censored:1.1), (mosaic:1.1), (bar censor:1.1), (underwear:1.1), (bra:1.1), (greyscale:1.05) , mutated hands and fingers, poorly drawn face, poorly drawn hands, poorly drawn feet, poorly drawn legs, longneck, big ears, tiling, bad toes, bad legs, bad anatomy, mutated feet and toes, poorly drawn toes, bad feet, bad art, text title signature, fat, fat legs Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 10.5, Seed: 2101647312, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/0a06e9438fa92374eddbc502690c955f.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, solo, cat ears, multicolored hair, ((gradient hair), white+(blue)+(pink:0.5) hair//), very long hair, messy hair, bangs, ahoge, ((gradient eyes), pink+light_blue eyes//), slit pupils, glowing eyes, 1fang, :o, white sweater,, masterpiece, best quality, Negative prompt: lowers,(worst quality, low quality:1.4),(bad hands, bad finger, bad fingers:1.2), (sfw:1.05),(artist name:1.1), (censored:1.1), (mosaic:1.1), (bar censor:1.1), (underwear:1.1), (bra:1.1), (greyscale:1.05) , mutated hands and fingers, poorly drawn face, poorly drawn hands, poorly drawn feet, poorly drawn legs, longneck, big ears, tiling, bad toes, bad legs, bad anatomy, mutated feet and toes, poorly drawn toes, bad feet, bad art, text title signature, fat, fat legs Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 10.5, Seed: 3271258500, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/dbedcbd5a402564e255d52fa9a3a4b34.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(((masterpiece))), (((best quality))), ((ultra-detailed)), (illustration), (1 girl), (solo), ((an extremely delicate and beautiful)), little girl, ((beautiful detailed sky)), beautiful detailed eyes, side blunt bangs, hairs between eyes, ribbons, bowties, buttons, bare shoulders, (small breast), blank stare, pleated skirt, close to viewer, ((breeze)), Flying splashes, Flying petals, wind Negative prompt: nsfw, owres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, missing fingers, bad hands, missing arms, long neck, Humpbacked, shadow, nude Steps: 20, Sampler: Euler a, CFG scale: 5.5, Seed: 270564269, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/84f3c1876d68c6db465185420d394176.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>Candid Shot At Girl Picture, Natural Volumetric Lighting And Best Shadow, Deep Depth Of Field, Chromatic Aberration, Portrait Of Original Character, Natural Volumetric Lighting And Best Shadows, Deep Depth Of Field, Sharp Focus, Portrait Of Stunningly Beautiful Petite Girl, Soft Delicate Beautiful Attractive Face With Alluring Red-Brown Eyes, Lovely Small Flat Breasts, Seductive Smiling, Open Mouth With Cute Fangs Out, Thick Layered Medium Twintail Brown Hair, White Hairband, Green Hair Ribbon Bows, Blush Eyeshadow With Thick Eyelashes, Pink Big Backpack, Green Bracelet, White Shirt, Short Sleeves, Neck Ribbon, Suspender Skirt, Bandaid On Knee, White Socks, Hands Up And Waving Hand, Children Playground At Apartment Residential Buildings, Jungle Gym With Swing, (Highest Quality, Amazing Details:1.4), Masterpiece, Bloom, Picturesque, Brilliant Colorful Paintings Negative prompt: (Worst Quality, Low Quality:1.4) Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 207061448, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/1195aadf4870b7a6cfe115ed16e5da8a.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>best quality, high resolution, distinct image, (beautiful detailed girl:1.1), (sidelighting:1.1), 1girl, bangs, red hair, medium hair, messy_hair, breasts, light smile, no pants, white shirt, panties, arms up, bent_over, looking at viewer, (outdoors:1.1), meme, midriff, navel, solo, standing, stomach, trembling Negative prompt: NG_DeepNegative_V1_75T, EasyNegative, extra fingers, fewer fingers, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, (worst quality, low quality:1.4), Negative2, (low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), bad composition, inaccurate eyes, extra digit,fewer digits, (extra arms:1.2), (bad-artist:0.6), bad-image-v2-39000 Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2041579246, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/aab93c53cfc372bc7c74eccfd4a3761a.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece, best quality, highres, portrait, 1girl, solo, short hair, looking at viewer, multicolored hair, orange hair, white hair, blue hair, braid, bangs, orange eyes, streaked hair, small breasts, breasts, long sleeves, (black hoodie:1.4), simple background, orange background, blush, smile, floral print on hoodie, Negative prompt: (worst quality, low quality:1.4), extra fingers, fewer fingers, watermark, EasyNegative, bad_prompt_version2 Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 4284525206, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/0a60e2caafecfc9801a15f3a0c3254a9.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, solo, long hair, skirt, outdoors, cloud, black hair, blue eyes, shirt, long sleeves, shoes, sky, tree, black skirt, full body, blue sky, bangs, blush, blue shirt, sneakers, standing, grass, white footwear, cloudy sky, day, print shirt, looking at viewer, walking Negative prompt: (worst quality, low quality:1.4), extra fingers, fewer fingers, watermark, EasyNegative, bad_prompt_version2 Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3244306190, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/ce4e7e24322a0a4806672a111c8e84e8.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>best quality, absurdres, 1girl, nanahi, green hairband bow, very long hair, yellow eyes, (light brown hair:1.1), hair between eyes, small breasts, green hood, zipper dress, upper body, open clothes, white strap dress, sitting, sitting on bed, bedroom, wide hips, thigh gap, (striped pink green white) (single thighhigh:1.2), short Negative prompt: (worst quality:1.4), (low quality:1.4) , (monochrome:1.2), (bad_prompt_version2:0.5), (black thighhigh:1.2) Steps: 24, Sampler: DPM++ 2M Karras, CFG scale: 7.5, Seed: 4142758332, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/2391ff275af0a0622529c15f6f28d3b3.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality, highres:1.2), 1girl, solo, looking at viewer, outdoors, sunset, witch_hat, single_braid, blonde hair, long hair, yellow eyes, large_breasts, blush, embarrassed, furrowed brow, smile, magical_girl, short_sleeves, kirisame marisa \\(cosplay\\), white_shirt, black_skirt, white_apron Negative prompt: EasyNegative,(worst quality, low quality:1.4), (bad-hands-5:0.8), logo, watermark, text Steps: 30, Sampler: Euler a, CFG scale: 8, Seed: 1440327336, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/4c9b06f1f883f7537396fcee36aba375.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl,ahoge,bangs,braid,day,detached sleeves,dragon girl,dragon horns,dragon tail,dress,hair tubes,highres,horns,long hair,long sleeves,looking at viewer,ocean,open mouth,outdoors,pointy ears,blue hair,smile,solo,standing,tail,very long hair Negative prompt: EasyNegative, bad anatomy, bad hands, extra digits, extra ears, Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1233626860, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/c0976905072a345ca59dbe908cac66d4.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality),ray tracing,absurdres, HDR,1girl, bangs, black hair, twintails, very_long_hair, black_skirt, blush, bow, bowtie,breasts, depth_of_field, hair_between_eyes, hair_ribbon, indoors, , long_sleeves, looking at viewer, , pleated_skirt, red bow, red bowtie, red_eyes, red ribbon, school_uniform, shirt, sidelocks, pleated skirt, solo, white_shirt,cowboy shot,happy,cute face,natural light Negative prompt: ng_deepnegative_v1_75t,EasyNegativeV2, bad_prompt_version2,(worst quality, low quality:1.6),(malformed hands:1.4),(poorly drawn hands:1.4),(mutated fingers:1.6),(extra limbs:1.35),(poorly drawn face:1.4),(bad hands:1.4),(malformed anatomy:1.4),(bad anatomy:1.4),(mutated anatomy:1.4), watermark,(mutated legs:1.6),(bad perspective:1.4),(bad body proportions:1.4), (bad proportion:1.4), (watermark:2.0), Steps: 25, Sampler: Euler a, CFG scale: 7, Seed: 1233264683, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/1cd4115fcff612aa592f5b456c2e94af.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>photo of a iom girl,stomach, wet, pretty_wet_body, sweat, shy, [exhibitionism], [medium\|small\|small] breasts, black_long_hair, bikini, pretentious_face, (embarrassed), black_hair, fox_ears, big_fox_tail, cowboy shot, extremely detailed CG unity 8k wallpaper, ((ultra-detailed)), (best illustration), (best shadow), ((an extremely delicate and beautiful)), ((cinematic light)), Negative prompt: lowres, bad anatomy, bad hands, bad proportions, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, poorly drawn hands, poorly drawn face, jpeg artifacts, signature, watermark, username, blurry, artist name, fat, thick eyebrows, clumped, ugly, plump, 3d, mutation, long neck, Humpbacked, (no face), monotonous color, anime screencap Steps: 20, Sampler: Euler a, CFG scale: 11, Seed: 968148509, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/9bae3e8f2e7e299d9cb1a4230a712255.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality), 1boy, solo, white short hair, wolf ears, wolf tail, long eyebrow, heterochromia, red eye on right eye, blue eye on left eye, white shirt, blue overalls, white-framed eyewear, purple beret on left head, neck bell, light smile, fantasy, castle Negative prompt: (worst quality:1.4), (low quality:1.4), (trembling:1.4), (cropped face:1.4), watermark, (realistic:1.2), lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, bell on the head Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 1674499086, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/2edacf26291e79c4e6a3433da967293d.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece, best quality, 4k, UHD, mishoujo, painting, beautiful eyes and detailed face, illustration, beautiful detailed, high resolution illustration, glowing_white_particles, 1girl, white hair, light purple eye, hair over one eye, short sidetail, baseball cap,expressionless, window shade, black jacket, chest rig, cyberpunk, techwear,(Impressionism:1.4), Vincent van Gogh Negative prompt: (Worst Quality, Low Quality:1.4), (Poorly Made Bad 3D, Lousy Bad Realistic:1.1) Steps: 20, Sampler: DPM++ SDE Karras, CFG scale: 7, Seed: 1968399838, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/a36882ee2f2ba3016d79f1cbca8a2cb6.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>bubble, rating:safe, air_bubble, underwater, 1girl, fish, long_hair, submerged, school_uniform, serafuku, solo, water, skirt, neckerchief, short_sleeves,(Impressionism:1.4), Negative prompt: (worst quality, low quality:1.4), EasyNegative , bad_prompt_version2 , nsfw, Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 9, Seed: 502967374, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/576bbb7ce55cae9fc93debee88866624.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(Overhead view),dynamic angle,ultra-detailed, illustration, close-up, straight on, 1girl, (fantasy:1.4), (azure blue eyes:1.233),Her eyes shone like dreamy stars,(glowing eyes:1.233),(beautiful and detailed eyes:1.1),(Silver hair:1.14),(messy hair,very long hair,french braid,hair between eyes,sidelocks), (+(bule hair flower:1.14)),(chiffon dress,bule flower pattern in uniform)/=(military uniform:1.24),(detached sleeves,wide sleeves),(fingerless gloves),choker,(miko thighhighs),High heeled boots,(expressionless,closed mouth),(standing), (classical Princess boudoir with dressing table\&lt;books\> and french window\&lt;a epic view outside the window\> in a white ancient palaces),(white flowers,bloom),(abysmal sea),(flowing water),(a dull blue world tree:1.14),(ruins),(night:1.2),dreamy,soul,(fluorescence),(flying translucent blue butterflies:1.15), [[delicate fingers and hands:0.55]::0.85],(detail fingers),(yubao:0.5) Negative prompt: (worst quality, low quality:1.4), monochrome, zombie, Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 8, Seed: 1178557168, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/fb3c5ceb5e53846c07051c215cd4d619.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>detailed,best quality,masterpiece,illustration,wallpaper,,1girl,solo,upper bodywhite bow,:d,smile,eyeliner,long hair, black hair,(ahoge:1.2),bangs,hair between eyes,gray inner hair, red eyes,looking at viewer,black sailor collar,black serafuku,long sleeves,dimly lit Negative prompt: (worst quality, low quality:1.4),nsfw,(bad_prompt),cropped,text,jpeg artifacts,signature,watermark,username,blurry,artist name,trademark,title,muscular,sd character,multiple view,Reference sheet,long body,malformed limbs,multiple breasts,cloned face,malformed,mutated,bad anatomy,disfigured,bad proportions,duplicate,bad feet,artist name,extra limbs,ugly,fused anus,text font ui,missing limb Steps: 20, Sampler: Euler a, CFG scale: 9, Seed: 3087905103, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/a04b53e500f94704599d89ca5d05c7d3.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>flower, nail_polish, plant, potted_plant, double_bun, flower_pot, vase, toenail_polish, animal_ears, rabbit_ears, rose, red_nails, leaf, red_flower, hydrangea, feet, tulip, bamboo, pink_flower, morning_glory, purple_flower, pink_rose, toenails, 1girl, long_hair, vines, blue_nails, toes, red_rose, thighhighs, bouquet, cactus, ivy, garden, soles, pink_nails, blue_eyes, barefoot, sitting, watering_can, yellow_flower, interlocked_fingers, black_legwear, palm_tree, looking_at_viewer, tanzaku, nail_art, tanabata, rabbit_girl, window, amiya_\\(arknights\\), lily_of_the_valley, camellia, silver_hair, solo, ribbon Negative prompt: EasyNegative, bad_prompt_version2, (worst quality:1.4), (low quality:1.4), (normal quality:1.4), lowres, skin spots, acnes, skin blemishes, age spot, glans,extra fingers, fewer fingers,strange fingers,((bad hand)),Hand grip,(lean),Extra ears,(Four ears),Strange eyes,(three arms),Many hands,(Many arms),((watermarking)), Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3712480245, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/b7a9fd6c8750b790fef64f6d78a47aed.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece,1girl, ((medium breasts)),Blue hair,yellow eyes, mature female, holding sickle, cat_ears,cat tail,cat girl,slit_pupils,t-shirt, skirt, white legwear, clubroom,spring,open coat, skirt lift, white panties, Negative prompt: EasyNegative,sketch, duplicate, ugly, huge eyes, text, logo, monochrome, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), crown braid, ((2girl)), (deformed fingers:1.2), (long fingers:1.2), (bad-artist-anime), bad-artist, bad hand,, ,bad_prompt_version2, Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1680240860, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/b3b6fddd2c9e26e84cccf4c7e30cbb8b.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece,1girl,solo,((in_tree)),white_hair,long_hair,white_dress,collarbone,mole_under_eyes,light_smile,long white dress,white_legwear,medium_breasts,off_shoulder,falling_leaf.flower,hair_ornament.sitting_on_branch,full_body,(uwabaki),red eyes,medium breasts, Negative prompt: EasyNegative,sketch, duplicate, ugly, huge eyes, text, logo, monochrome, worst face, (bad and mutated hands:1.3), (worst quality:2.0), (low quality:2.0), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), crown braid, ((2girl)), (deformed fingers:1.2), (long fingers:1.2), (bad-artist-anime), bad-artist, bad hand,, ,bad_prompt_version2, Steps: 20, Sampler: Euler a, CFG scale: 10, Seed: 513010126, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/1b369caed6b9eb19ebd3fdb7f7961482.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality:1.3), (ultra detailed, cinematic lighting:1.2), 1girl, solo, blonde hair, long hair, blue eyes, fox ears, fox tail, kimono, black thighhighs, shrine, cherry blossoms, sakura blossoms leaves, outdoors, dynamic angle Negative prompt: (worst quality, low quality:1.4), lowres, (bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, mutated hands and fingers, interlocked fingers, twisted fingers, excessively bent finger:1.4), cropped, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3543207004, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/d3c8718243a5bfd5e4179a2cd778c656.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, black_bra, black_panties, bra, breasts, head_out_of_frame,blue jacket, lace, lace_trim, long_hair, medium_breasts, mole_on_breast, navel, open_clothes, open_jacket, panties, panties_under_pantyhose, pantyhose, police, police_uniform, short_sleeves, solo, underwearal_youtuber, yellow_eyes, Negative prompt: easynegative Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 2063888222, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/e5b519d5d8a7bc1d063ce67251d26e98.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, ultra high res, best quality:1.1), (flat color), 1girl, solo, teen, cowboy shot, (depth of field:1.2), (night), (long coat), downtown, (street light:1.1), (Fantastic lighting), looking at viewer, black hair, long hair, [smile], (Closed mouth) Negative prompt: EasyNegative, bad-hands-5, (worst quality, low quality:1.4), (monochrome:1.2), Steps: 50, Sampler: Euler a, CFG scale: 5, Seed: 1629121239, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/cc9735166a23fe7286cb09655f2c3ae3.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>Loli, solo focus, full body, sitting, dynamic angle, white hair, flat chest, frilled, 3yo, brown hair, long hair, night, starry sky, dark, sleepy, want to sleep, animal ears hood, A young girl in pajamas holding a large stuffed animal, with a shy expression on her face, in a bedroom setting, The composition should exude a blend of sensuality and innocence, The background should be visually captivating, Negative prompt: EasyNegative Steps: 28, Sampler: Euler a, CFG scale: 7, Seed: 2643616813, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/2dd6923b24b0b04b74fe7555846db15e.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality:1.3), (ultra-detailed:1.3), 1girl, solo, (white hair, messy hair, long hair), (angel wings, angel halo), flat chest, yellow eyes, (white shirt, black necktie, black coat, open coat), cowboy shot, cinematic lighting, (((glowing light particles))), (arms behind back), dynamic angle, Negative prompt: (worst quality, low quality:1.4), (bad anatomy, bad hands, text, error, bad fingers, missing fingers, extra digit, fewer digits:1.4), lowres, cropped, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1262507504, Size: 640x960, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/29d524d2009a9c9616c8bebe0460e3aa.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>vector art with clean lines, well-put-together art, 1girl, :3, ?, chibi, bangs, blush, close-up, closed_mouth, eyebrows_visible_through_hair, hair_between_eyes, hat, heart, inubashiri_momiji, looking_at_viewer, red_eyes, short_hair, silver_hair, solo, tokin_hat, white_hair, wolf_ears, upper_body, no mistakes in the artwork, the artwork is a masterpiece with no flaws, is the best and highest quality art in the anime style, the most beautiful anime style art ever seen, award winning anime that is visually stunning, the art has the best transition between two shapes of colors, depth, art that was drawn by a pro artist Negative prompt: the body looks like a ragdoll, terrible worst bad horrible ugly transition between two shapes of colors in art, a drawing from the worst artist, poor lighting, 360p 144p image quality, lowres image, low bad image quality, bad face, 3d render, the art is in b&amp;w, emotionless, the image looks poorly composited, is logo art, an infographic, the forms lines edges colors and shapes in art looks bad worst poorly made wobbly distorted deformed up close and far away, is in the nude with no bra or panties, abstract, errors, pencil drawn sketch, line art, digital drawings Steps: 20, Sampler: Euler a, CFG scale: 10.5, Seed: 2615471327, Size: 960x640, Model hash: 5801911d1a, Model: [M]LoliV1_Fix_FP16, Clip skip: 2, ENSD: 31337
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/619abf360ebdff15b153655cd4e4adc0.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>((best quality)),((world masterpiece)),((illustration)),beautiful detailed,colourful,extremely detailed 8K wallpaper,finely detailed,dramatic light,intricate details, ((ultra-detailed)), 1girl, bangs, belt, bird, blue_hair, blue_sky, blush, braid, cloud, confetti, day, dress, frills, hair_ribbon, hat, looking_at_viewer, microphone, mini_hat, music, open_mouth, outdoors, palm_tree, ribbon, sailor_collar, sailor_dress, seagull, short_hair, singing, sky, sleeveless, sleeveless_dress, smile, solo, stage, sunlight, tree, wrist_cuffs, yellow_eyes Negative prompt: (worst quality, low quality:1.4), (EasyNegative:1.2),(badhandv4:1.2) Steps: 30, Sampler: UniPC, CFG scale: 9, Seed: 3892168508, Size: 512x768, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/814972d5ddd13b1327ee6ebd249f833f.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>((best quality)),((world masterpiece)),((illustration)),beautiful detailed,colourful,extremely detailed 8K wallpaper,finely detailed,dramatic light,intricate details, ((ultra-detailed)), 1girl, blue_dress, blue_eyes, blue_hair, blush, dress, long_sleeves, outdoors, pond, short_hair, sitting, soaking_feet, solo, twintails, two_side_up, water Negative prompt: (worst quality, low quality:1.4), (EasyNegative:1.2),(badhandv4:1.2) Steps: 30, Sampler: Euler a, CFG scale: 9, Seed: 1805748580, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/e4adcd6075c48b479cadb2aa978d173a.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>((best quality)),((world masterpiece)),((illustration)),beautiful detailed,colourful,extremely detailed 8K wallpaper,finely detailed,dramatic light,intricate details, ((ultra-detailed)), 1girl, :d, accordion, bangs, blue_butterfly, blunt_bangs, blurry, blurry_foreground, bug, butterfly, butterfly_on_head, crown, cup, day, dress, drinking_glass, eyebrows_visible_through_hair, flower, green_dress, green_eyes, head_tilt, instrument, light_particles, light_rays, long_hair, looking_at_viewer, low_twintails, mini_crown, music, open_mouth, outdoors, petals, pinafore_dress, pink_hair, plate, playing_instrument, shiny, shiny_hair, shirt, sitting, sleeves_past_elbows, smile, solo, streamers, sunbeam, sunlight, table, twintails, yellow_shirt Negative prompt: (worst quality, low quality:1.4), (EasyNegative:1.2),(badhandv4:1.2) Steps: 30, Sampler: Euler a, CFG scale: 9, Seed: 3133137646, Size: 512x768, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/b9c0bc87e6c619288bab0dd7dbe8fa1d.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality, ultra-detailed, best shadow), (detailed background,dark fantasy), (beautiful detailed face), high contrast, (best illumination, an extremely delicate and beautiful), ((cinematic light)), colorful, hyper detail, dramatic light, intricate details, (1girl, solo,black hair, sharp face,low twintails,red eyes, hair between eyes,dynamic angle), blood splatter, swirling black light around the character, depth of field,black light particles,(broken glass),magic circle, Negative prompt: (worst quality, low quality:1.4), zombie, (interlocked fingers), Steps: 25, Sampler: Euler a, CFG scale: 7, Seed: 824097015, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/8821f34ad30fc511a18492d6a63de4a0.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, autumn, autumn_leaves, bangs, beach, blue_sky, blush, breasts, brown_hair, closed_mouth, cloud, cloudy_sky, collarbone, day, dress, field, flower, flower_field, horizon, lake, leaf, looking_at_viewer, mountain, mountainous_horizon, ocean, outdoors, palm_tree, petals, plant, red_flower, short_hair, skirt_hold, sky, smile, solo, standing, sunset, tree, twilight, water, white_dress, perfect eyes Negative prompt: extra fingers, fewer fingers, bad-hands-5, by bad-artist, (bad eyes:1.2), (misfigured pupils:1.2), (bad clothing:1.3), (undetailed clothing:1.3), ng_deepnegative_v1_75t, verybadimagenegative_v1.3, (nonsensical backrounds:1.2), (bad backrounds:1.2), (bad shadows:1.2), (bad anatomy:1.1) Steps: 30, Sampler: Euler a, CFG scale: 8, Seed: 1739341684, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/90e764eb32369c9d2173b2b41247bbc3.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece, best quality, 1girl, solo, long hair, alternate costume, alternative hair, twin tails, hair buns, two tone hair, multicolored hair, pink hair, two colored hair, streaked hair, gold hair, gold eyes, bangs, makeup, black lipstick, mascara, eyeshadow, cross necklace, hair bow, front bow, lace jacket, lace gloves, fishnets, black leggings, gothic attire, dynamic angle, side lighting, shiny skin, detailed eyes, detailed face, water flowing, wind swept hair, glitter , Negative prompt: (bad_prompt_version2:0.8), (low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), nsfw, nude, naked , nipple, open clothes, bad composition, inaccurate eyes, extra digit, fewer digits, (extra arms:1.2) ng_deepnegative_v1_75t negprompt5 bad_prompt_version2 Steps: 30, Sampler: Euler a, CFG scale: 7, Seed: 3282137259, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/305c279169fc23ef167fd7c01ddef4b0.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>Beetlejuice, official art, 1girl, solo,(demonic, semi realistic, demonic, shiny skin, textured skin),holographic eyes, heterochromia, purple eyes, striped jacket,striped shirt, two tone hair, streaked hair, multicolored hair, red hair, green hair, wild hair, evil scene,teeth, side lighting, ray tracing, depth of field, solo, extreme light and shadow, masterpiece, post apocalyptic, sexy, beautiful , scary, rich in detail,(detailed eyes), (handsome) detailed, (dirt splotches), (horror theme), (beetlejuice), detailed eyes,(straight-on),(masterpiece), (best quality), (ultra-detailed), (best illustration),(best shadow),rim lighting, beetlejuice, ((Beetlejuice)), crazy grin, crazy expression, Negative prompt: easynegative, worst quality, normal quality, split_screen, framed border, blur, childlike paintings, sketches, (worst quality, low quality, normal quality:1.7), lowres, normal quality, ((monochrome)), ((grayscale)), (worst quality, low quality:1.3) Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1475550087, Size: 512x768, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/7af893eb46758862484dcb68e7737acc.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, best quality), ((1girl, (mature female) long hair), (star-shaped pupils, +_+, symbol-shaped pupils, sparkling eyes)), (looking at viewer, light smile, off shoulder), (multicolored background, abstract background, chromatic aberration), Negative prompt: (EasyNegative), (bad-hands-5, interlocked fingers), (worst quality, low quality:1.4), (kid, loli), (mutation, mutant), (big eyes, large breasts, tight dress), Steps: 30, Sampler: Euler a, CFG scale: 6, Seed: 3162107392, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/7d2267f6324e9302cd2bc279b2089917.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>absurdity,(fantasy:1.2),In a splendid fantasy world of the day, vibrant and vivid colors fill the surroundings, BREAK,and the essence of nature thrives. Graceful fairies flutter about, BREAK, and magical flowers bloom in abundance. The sky is clear, BREAK, and the sunlight bathes everything in a warm glow, BREAK, Beautiful forests and expansive green meadows stretch out, BREAK, offering glimpses of fantastical creatures and miraculous landscapes ,BREAK, In this world, hope and joy abound, creating a serene everyday life filled with happiness and peace, 1girl, (romance:1.8),(Barrie Cooke:1.5),(Montreal:1.3),(grim dark:1.5),(tuba),(Montreal:1.2),(flowers:1.3),BREAK Negative prompt: ( EasyNegative:1.2), nsfw, nipples, pubic hair,nude Steps: 20, Sampler: Euler a, CFG scale: 9.5, Seed: 2147739825, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/d549c2e968e95aa654f211b60bb3b749.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>((((dramatic))), (((gritty))), (((intense))) film poster featuring a young woman as the central character. She stands confidently in the center of the poster, wearing a stylish and edgy outfit, with a determined expression on her face. The background is dark and gritty, with a sense of danger and intensity. The text is bold and attention-grabbing, with a catchy tagline that adds to the overall feeling of drama and excitement. The color palette is mainly dark with splashes of vibrant colors, giving the poster a dynamic and visually striking appearance,tachi-e (magazine:1.3), (cover-style:1.3), fashionable, woman, vibrant, outfit, posing, front, colorful, dynamic, background, elements, confident, expression, holding, statement, accessory, majestic, coiled, around, touch, scene, text, cover, bold, attention-grabbing, title, stylish, font, catchy, headline, larger, striking, modern, trendy, focus, fashion, Negative prompt: (mutated hands and fingers:1.5 ),(mutation, poorly drawn :1.2), (long body :1.3), (mutation, poorly drawn :1.2) , liquid body, text font ui, long neck, uncoordinated body,fused ears,huge breasts,((((ugly)))),one hand with more than 5 fingers, one hand with less than 5 fingers Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 4025171226, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/ed6b3d894e6b4548f671ab09b662e3e2.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(1boy, 1girl), cat ears, short hair, silver hair, white hair, purple eyes, masterpiece, pov, medium breast, absurdres, messy hair, cute smile, winking, blushing, nice hands, simple background, Japanese clothes, kimono, side-by-side, holding hands, floating heart, heart earrings, white hair, full-face blush, looking at another, face-to-face, Negative prompt: (low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), bad composition, inaccurate eyes, extra digit, fewer digits, (extra arms:1.2), nsfw, v, double v, black hair, purple hair, yuri, Steps: 20, Sampler: Euler a, CFG scale: 7.5, Seed: 2833421800, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/34d20c6d099d4c95e503e954b9ff987d.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>cat ears, short hair, silver hair, white hair, purple eyes, masterpiece, pov, medium breast, absurdres, messy hair, cute smile, winking, blushing, nice hands, black turtleneck, black hair simple background, Japanese clothes, kimono, pov, pointing at self, pointing at her breasts, Negative prompt: (low quality, worst quality:1.4), (bad anatomy), (inaccurate limb:1.2), bad composition, inaccurate eyes, extra digit, fewer digits, (extra arms:1.2), nsfw,, lowres, (bad anatomy:1.1025), (bad hands:1.1025), text, missing finger, extra digits, fewer digits, blurry, (mutated hands and fingers:1.1025), (poorly drawn face:1.05), (mutation:1.1025), (deformed face:1.1025), (ugly:1.05), (bad proportions:1.1025), (extra limbs:1.1025), extra face, (double head:1.05), (extra head:1.05), (extra feet:1.1025), monster, logo, cropped, worst quality, low quality, normal quality, jpeg, humpbacked, long body, long neck, (jpeg artifacts:1.1025), Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 372331328, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.2.1
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/ef998c3ecf10276fccf713aefc322cc1.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>((best quality)), ((masterpiece)), (detailed), alluring succubus, ethereal beauty, perched on a cloud, (fantasy illustration:1.3), enchanting gaze, captivating pose, delicate wings, otherworldly charm, mystical sky, (Luis Royo:1.2), (Yoshitaka Amano:1.1), moonlit night, soft colors, (detailed cloudscape:1.3), (high-resolution:1.2) Negative prompt: EasyNegative, (worst quality, low quality:1.4), [:(badhandv4:1.5):27],nsfw Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 396392455, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Denoising strength: 0.7, Clip skip: 2, ENSD: 31337, Hires upscale: 2, Hires upscaler: Latent, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/07424e64c90caaaee86acc848711a818.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, top quality, best quality, official art, beautiful and aesthetic:1.2),1girl, tattoo, solo, japanese clothes, hair ornament, unsheathing, black hair, sheath, back tattoo, blue eyes, off shoulder, bare shoulders, looking back, from behind, flower, looking at viewer, holding, makeup, indoor, Negative prompt: (worst quality, low quality:2), NSFW,monochrome, zombie,overexposure, watermark,text,bad anatomy,bad hand,extra hands,extra fingers,too many fingers,fused fingers,bad arm,distorted arm,extra arms,fused arms,extra legs,missing leg,disembodied leg,extra nipples, detached arm, liquid hand,inverted hand,disembodied limb, oversized head,extra body,extra navel,(hair between eyes),sketch, duplicate, ugly, huge eyes, text, logo, worst face, (bad and mutated hands:1.3), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, Steps: 20, Sampler: Euler a, CFG scale: 7.5, Seed: 234372863, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/f7e9f247a05598b67363b0b990e52fba.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(masterpiece, top quality, best quality,watercolor (medium),official art, beautiful and aesthetic:1.2),(1girl:1.3), (fractal art:1.3),upper body, from side, looking at viewer,patterns,(rainbow color Hair,colorful hair,half blue and half pink hair:1.2),water,liquid, cloud,colorful, starry,stars, Negative prompt: (worst quality, low quality:2), monochrome, zombie,overexposure, watermark,text,bad anatomy,bad hand,extra hands,extra fingers,too many fingers,fused fingers,bad arm,distorted arm,extra arms,fused arms,extra legs,missing leg,disembodied leg,extra nipples, detached arm, liquid hand,inverted hand,disembodied limb, small breasts, loli, oversized head,extra body,completely nude, extra navel,easynegative,(hair between eyes),sketch, duplicate, ugly, huge eyes, text, logo, worst face, (bad and mutated hands:1.3), (blurry:2.0), horror, geometry, bad_prompt, (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4), ((2girl)), (deformed fingers:1.2), (long fingers:1.2),(bad-artist-anime), bad-artist, bad hand, extra legs , Steps: 28, Sampler: Euler a, CFG scale: 7.5, Seed: 1844754387, Size: 512x768, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/edf792ebbc696889bbdb6b7d3622b4cd.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl, (ishida sui: 1.2), (sketch:1), limited palette, red eyes, silver hair, shiny skin, hair between eyes, empty eyes, (lips:0.4), (watercolor:0.8), white background, (ink splatter: 1.1), from side, hair flower, (carne griffiths:1.1), red flower, masterpiece, best quality, Negative prompt: lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1048346643, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/56f2c9341026ac860f63b3af99640b28.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(Loli:1.4), (Solo focus girl:1.2), blue eyes, outdoors, long blonde hair, solo, tall tower, rose, crown, gown, smile, night, balcony, fringe, bare arms, open mouth, puffy sleeves, pink gown, bricks, moon, standing, trellis, sweetheart neckline, courtyard BREAK A little princess with blue eyes and long blonde hair is standing on a balcony of a tall tower in a castle courtyard at night. She is wearing a pink gown with puffy sleeves and a sweetheart neckline. She has a crown on her head and a fringe. She is smiling with her mouth open, There are bricks, a trellis and the moon around her. Negative prompt: (worst quality:1.4), (low quality:1.4),(monochrome:1),bad-hands-5, EasyNegative, white hair, hair, Steps: 18, Sampler: Euler a, CFG scale: 7, Seed: 2195927774, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/0bbdb1d58dde45e836fbccd9633a67bb.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>beautiful illustration, best quality, cute petit girl, (transform sequence), transform magical girl, chibi, white magical girl, fractal art, albino, babyface, long pure white and red mesh hair, beautiful detailed red eyes, cinematic lighting, cowboy shot, looking at viewer, from bottom, happy Negative prompt: EasyNegativeV2, negative_hand-neg, worst quality, low quality, logo, text, watermark, username, male, inaccurate legs and hands and fingers, extra legs, extra arms, extra fingers, Steps: 37, Sampler: Euler a, CFG scale: 7, Seed: 3487240517, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/c920da3f0da1cf33cd6f92cb87c52a02.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>masterpiece,best quality, Sunset, lens flare ,retro townscape, (very cute girl, looking back, blush), flat chest, (cherry blossom:1.2), pink beret, gothic pink dress, frills, ruby eyes, long blue hair, floating petals, Negative prompt: (worst quality:1.4), (stuck hands,melted finger,Stuck fingers:1.3), (monochrome), Steps: 20, Sampler: Euler a, CFG scale: 8, Seed: 805192713, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/2203c74fa7c203d5bab271358fe303c5.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1girl ,bare shoulders,black hair ,holding_bouquet ,branch ,breasts ,colored inner hair, colorful ,fish ,hanfu,dress,long dress ,mountain,pool ,((white_see-through dress)),strapless dress , tree , (waterfall ),cowboy shot, standing, from above, bare legs, Negative prompt: EasyNegative, (worst quality:1.4), (low quality:1.4), (normal quality:1.4), lowres, Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 3907337926, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/99fa036151ef55eae97f672ed9ca2276.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>front view,(black and white:1.2), partially colored, motion picture,shrine,red wood wall,(profile:1.1), red object on hand, 1girl,solo,red eyes,light eyes,white hair,(flat chest:1.2),(hanfu,detached sleeves,side slit:1.4),(nine white tails:1.45),(white fox ears:1.2),([red bow hair ornament:red ribbon:0.5]:1.2),(masterpiece, best quality, detailed:1.4), (extremely detailed 8K game cg wallpaper:1.1), (an extremely delicate and beautiful) Negative prompt: EasyNegativeV2,lowres,simple background,bad anatomy,bad hands,text,error,missing fingers,extra digit,fewer digits,cropped,worst quality,low quality,normal quality,jpeg artifacts,blurry,extra legs,extra feet,extra arms,extra fingers,missing legs,missing arms,ugly ,huge breasts,monochrome,(no humans:1.5),mix,extra digit,(nipples:1.2),bad-hands-5, bad-artist Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1946117409, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/fd594b3494e68c5fc23333d9f198723c.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>1gril,clear face,High definition,(white background:1.2),paint effect, long hair girl with white mixed with rainbow color flowing hair and starry color clothes,Beautiful hair,white hrie,rainbow hair Negative prompt: lowres, bad anatomy, bad hands, text,error, missing fngers,extra digt ,fewer digits,cropped, wort quality ,low quality,normal quality, jpeg artifacts,signature,watermark, username, blurry, bad feet,nsfw,Deformed body,spectacles,Deformed face,blue face,dark background,black background,Rainbow backgroundm,cover the body Steps: 20, Sampler: Euler a, CFG scale: 12, Seed: 270507485, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/86bfe20848e808a1d4fab92dd3c9db78.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>(((masterpiece))),(((crystals texture Hair))),(((((extremely detailed CG))))),((8k_wallpaper)), (1 girls:1.5),big top sleeves, floating,beautiful detailed eyes, overexposure, side blunt bangs, buttons, bare shoulders,(loli),light shafts, soft focus, character focus,wings,(((Transparent wings))), [[((Wings made of golden lines,angel wing,gold halo around girl,many golden ribbon,Aureate headgear,gold magic circle in sky,ight, black sky):1.3):((galaxy background, snowflakes, night sky, black pupils, starts sky background, stars behind girl, view on sky,standing):0.8)],[(Elegant hair,Long hair,The flying golden lines,Messy golden lines,halo,hairs between eyes,Small breasts,ribbons, bowties,red eyes, golden pupil, white hair,flowing hair,disheveled hair,lowing long hair):(Delicate arms and hands):0.8] Negative prompt: (mutated hands and fingers:1.5 ),(mutation, poorly drawn :1.2), (long body :1.3), (mutation, poorly drawn :1.2) , liquid body, text font ui, long neck, uncoordinated body,fused ears,huge breasts,((((ugly)))),one hand with more than 5 fingers, one hand with less than 5 fingers Steps: 20, Sampler: Euler a, CFG scale: 12, Seed: 3835497837, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/399732b900971b93fba58897858e0e42.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>extremely delicate and beautiful,extremely detailed,official art, amazing,masterpiece,growth,visual impact,best quality,colorful refraction,dark intense shadows,colorful, hdr,ray tracing,blurry_background,blurry,depth of field, ultra-detailed,highly detailed, Amazing finely detail,(((loli))),(((child))), pink_rose, rose, pink_flower, flower, red_rose, 1girl, purple_rose, blue_rose, white_rose, long_hair, panties, underwear, breasts, solo, low_ponytail, looking_at_viewer, low_twintails, thigh_strap, green_flower, rose_petals, pubic_tattoo, navel, bare_shoulders, white_panties, thorns, hair_ornament, ribbon, collarbone, twintails, purple_flower, holding_flower, parted_lips, red_flower, side-tie_panties, cowboy_shot, babydoll, medium_breasts, wings, bangs, green_eyes, eyebrows_visible_through_hair, curtains, blush Negative prompt: (worst quality, low quality:1.4),EasyNegative, lanjiao3 lanjiao4 lanjiao5,(mutated hands and fingers:1.5), (long body :1.3), (mutation, poorly drawn:1.2), (bad and mutated hands:1.3), (bad hands), (missing fingers), multiple limbs, bad anatomy, (interlocked fingers:1.2), Ugly Fingers, (extra digit and hands and fingers and legs and arms:1.4),(deformed fingers:1.2), (long fingers:1.2),normal quality, letterbox,deformed,out of frame,60s,70s,80s,90s,00s,ugly,morbid, mutation, arthropod girl,arthropod limbs, disfigured,extra_arms,extra_ears,extra_breasts,(extra_legs:1.2), Steps: 21, Sampler: Euler a, CFG scale: 7, Seed: 292695147, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 63762, Eta: 0.445, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><figure><img src="@source/posts/media/c34f756821f26544d5f58d18ddf7cdc4.png" alt="IMG_256" tabindex="0" loading="lazy"><figcaption>IMG_256</figcaption></figure>
<div class="language-txt line-numbers-mode" data-ext="txt"><pre v-pre class="language-txt"><code>official art,(white background:1.2), Brilliant light and shadow,Back lit,1girl, side blunt bangs,hairs between eyes,Red eyes,delicate face, ribbons,White Dress, bowties, buttons, bare shoulders,Detached Sleeve,(small breast), ((breeze)), Flying splashes,wind,Long flowing hair,(Broken glass),Grey hair,The flying water,Hair covering your body,The flying red ribbon, (Ink painting style),(Glitch Art):1.08), [:(Delicate arms and hands):0.8] Negative prompt: mutated hands and fingers:1.5 ),(mutation, poorly drawn :1.2), (long body :1.3), (mutation, poorly drawn :1.2) , liquid body, text font ui, long neck, uncoordinated body,fused ears,huge breasts,((((ugly)))),one hand with more than 5 fingers, one hand with less than 5 fingers,Oblique body,sea Steps: 50, Sampler: Euler a, CFG scale: 6.5, Seed: 4000138370, Size: 640x960, Model hash: 8c3643324f, Model: KawaICE_CH_FP16, Clip skip: 2, ENSD: 31337, Version: v1.3.0
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><p><img src="@source/posts/media/327ee7ffab91a60f2b545333d6a50882.png" alt="IMG_256" loading="lazy"><br>
`</p>
</div></template>


