export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/README.md"]],
  ["v-184f4da6","/intro.html",{"v":"/assets/images/cover3.jpg","e":"<h1> 介绍页</h1>\n<p>我是一个爱好科技的有远大抱负的苦命人。</p>\n<p>人工智能技术的快速发展已经成为了当今世界科技领域的热点话题。而在人工智能领域中，AIGC (Artificial Intelligence Global Community) 作为全球最大的人工智能社区之一，其发展前景备受关注。</p>\n<h2> 一、AIGC 的概述</h2>\n<p>AIGC 成立于2017年，是全球最大的人工智能社区之一。该社区致力于推动人工智能技术的发展和应用，并通过开展各种活动、交流和合作来促进各国在人工智能领域的合作与发展。目前，AIGC 在全球范围内拥有超过100万会员，覆盖了全球60多个国家和地区。</p>","y":"a","t":"介绍页","i":"circle-info"},[":md"]],
  ["v-2e3eac9e","/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-1473bf53","/demo/",{"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li>\n<p><a href=\"/demo/markdown.html\" target=\"blank\">Markdown 展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/page.html\" target=\"blank\">页面展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/disable.html\" target=\"blank\">禁用展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/encrypt.html\" target=\"blank\">加密展示</a></p>\n</li>\n</ul>","y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"c":["使用指南"],"g":["禁用"],"e":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"c":["使用指南"],"g":["文章加密"],"n":true,"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"c":["使用指南"],"g":["Markdown"],"e":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你应该创建和编写 Markdown 文件，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"a":"Ms.Molingrio","d":1689120000000,"l":"2023年7月12日","c":["使用指南"],"g":["页面配置","使用指南"],"u":true,"v":"/assets/images/cover1.jpg","e":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","y":"a","t":"这是一条测试","i":"file","O":1},[":md"]],
  ["v-7c9e35cc","/posts/husky.html",{"d":1689206400000,"l":"2023年7月13日","c":["哈士奇担任警察的可行性研究"],"g":["狗狗","哈士奇","警察"],"e":"<p>以下是关于哈士奇担任警察的可行性研究的ppt提纲：</p>\n<h1> 哈士奇担任警察的可行性研究</h1>\n<h2> 背景介绍</h2>\n<ul>\n<li>近年来，越来越多的警局开始使用犬只作为辅助工具</li>\n<li>哈士奇因其聪明、灵活、勇敢等特点备受青睐</li>\n<li>但是，哈士奇是否真的适合担任警察？需要进行可行性研究</li>\n</ul>\n<h2> 研究内容</h2>\n<ol>\n<li>哈士奇在警察工作中的优缺点分析</li>\n<li>哈士奇训练方案设计</li>\n<li>哈士奇在实际工作中的表现评估</li>\n</ol>\n<h2> 哈士奇在警察工作中的优缺点分析</h2>","y":"a","t":"哈士奇担任警察的可行性研究","i":"pen-to-square"},[":md"]],
  ["v-24b7c48d","/posts/dragonfruit.html",{"d":1689292800000,"l":"2023年7月14日","c":["vpn"],"g":["vpn","机场"],"v":"/g.jpg","e":"<h1> VPN机场汇总</h1>\n<h2> <a href=\"https://1.fish\" target=\"_blank\" rel=\"noopener noreferrer\">中国国际机场</a></h2>\n<p>提供试用流量<br>\n提供免流教程</p>\n<h2> <a href=\"https://dhh.wtf\" target=\"_blank\" rel=\"noopener noreferrer\">大航海</a></h2>\n<p><code>1x</code> <code>3x</code> <code>0.1x</code></p>\n<ol>\n<li><a href=\"https://t.me/DHH6666\" target=\"_blank\" rel=\"noopener noreferrer\">Telegram群组</a></li>\n<li>关于流量倍率，节点的流量倍率均标注于节点名称后方，如x10，则您使用1G流量将会以10G流量扣费。</li>\n<li>原则上不限制设备数量，但是严禁共享节点。</li>\n<li>如无法使用节点，可通过工单反馈，建议提供使用的浏览器，软件，以及节点等信息，如未提供任何信息，可能会直接被关闭工单。</li>\n</ol>","y":"a","t":"VPN机场汇总","i":"pen-to-square"},[":md"]],
  ["v-f0ec4556","/posts/strawberry.html",{"e":"<h1> 歌单</h1>\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"450\" height=\"520\" src=\"//music.163.com/outchain/player?type=0&amp;id=7199817011&amp;auto=1&amp;height=430\"></iframe>\n","y":"a","t":"歌单"},[":md"]],
  ["v-df8b6e0c","/posts/tomato.html",{"d":1689552000000,"l":"2023年7月17日","c":["随笔"],"g":["emotion","damage"],"u":true,"e":"<h1> 随笔</h1>\n<figure><figcaption></figcaption></figure>\n<h2> I</h2>\n<p>无尽的阴郁将光线吞没，沉默着，却隆隆作响。</p>\n<p>人们并不清楚自己的祖先从什么时候就已经出现了，也从不追究历史长河中究竟丧失了多少人。“寿命”就如同上帝给人们戴上的枷锁，但也如同流水一般，将万物更迭。新的事物以及思想因此不断地被创造。</p>\n<p>弗莱格听闻村里面的老人说，每个人的一辈子都是上天注定的，无论历史怎样顺延，每一个前进的步伐都好像是提前写入了剧本。老人同时哀叹自身的渺小与对未来的迷茫无力。当然，弗莱格本人是不太相信这些的。他觉得很多东西可以被上天注定，唯独命运不可以。每个人应当有着创造自己命运的能力与责任。因此，他也并不是一个循规蹈矩的人。他不希望每次站在河畔，山崖边的时候，看河流永远流向一个方向，看太阳照常起落，就如同再看一遍尘封的录像带一样。</p>","y":"a","t":"随笔","i":"pen-to-square"},[":md"]],
  ["v-6408b763","/posts/elementslaw.html",{"a":"Ms.Molingrio","d":1689379200000,"l":"2023年7月15日","c":["使用指南"],"g":["ai","aigc","使用指南","stable diffusion"],"u":true,"v":"/aa.jpg","e":"<h1> 錾制元素法典 - Stable Difussion二次元通用模板</h1>\n<h2> 说明</h2>\n<p><code>Civitai&amp;社区图片常用/好用二次元parameters合集。</code></p>\n<p><code>本文中所有资料任何权益不属于整理者本人，形式上借鉴《元素法典》</code></p>\n<ul>\n<li><strong>除内容本身外，最终解释权归 錾制千秋yuno779 所有</strong></li>\n<li><strong>合集内容为二次元相关tag串合集，最好使用二次元模型而非3D</strong></li>\n<li><strong>大部分示例图为KawaICE模型生成:</strong><a href=\"https://civitai.com/models/51057/\" target=\"_blank\" rel=\"noopener noreferrer\"><strong>https://civitai.com/models/51057/</strong></a></li>\n<li><strong>本tag集会持续整理，详情链接：<a href=\"https://civitai.com/models/62473\" target=\"_blank\" rel=\"noopener noreferrer\">https://civitai.com/models/62473</a></strong></li>\n<li><strong>本parameters集不含有NSFW内容</strong></li>\n<li><strong>由于存在不良商家拿着本文去坑其小白的钱，故限制合集转载：</strong></li>\n<li><strong>《CIVITAI法典》第一发布链接：<a href=\"https://civitai.com/models/62473\" target=\"_blank\" rel=\"noopener noreferrer\">https://civitai.com/models/62473</a></strong></li>\n<li><strong>其余均为转载，[允许任何不含盈利行为的转载]</strong></li>\n<li><strong>禁止任何形式以此获取收益，遇到不良商家请直接举报！</strong></li>\n</ul>","y":"a","t":"錾制元素法典 - Stable Difussion二次元通用模板","i":"file","O":2},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-e1e3da16","/posts/",{"y":"p","t":"Posts"},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":0},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":0},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":0},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":0},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":0},[]],
  ["v-03d57386","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"使用指南 分类","I":0},["/category/使用指南/"]],
  ["v-83e1f92e","/tag/%E7%A6%81%E7%94%A8/",{"y":"p","t":"标签: 禁用","I":0},["/tag/禁用/"]],
  ["v-5e7d3ae0","/category/%E5%93%88%E5%A3%AB%E5%A5%87%E6%8B%85%E4%BB%BB%E8%AD%A6%E5%AF%9F%E7%9A%84%E5%8F%AF%E8%A1%8C%E6%80%A7%E7%A0%94%E7%A9%B6/",{"y":"p","t":"哈士奇担任警察的可行性研究 分类","I":0},["/category/哈士奇担任警察的可行性研究/"]],
  ["v-1e447d61","/tag/%E6%96%87%E7%AB%A0%E5%8A%A0%E5%AF%86/",{"y":"p","t":"标签: 文章加密","I":0},["/tag/文章加密/"]],
  ["v-65f6c1d3","/category/vpn/",{"y":"p","t":"vpn 分类","I":0},[]],
  ["v-484552dc","/tag/markdown/",{"y":"p","t":"标签: Markdown","I":0},[]],
  ["v-60649a06","/category/%E9%9A%8F%E7%AC%94/",{"y":"p","t":"随笔 分类","I":0},["/category/随笔/"]],
  ["v-a378ad66","/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/",{"y":"p","t":"标签: 页面配置","I":0},["/tag/页面配置/"]],
  ["v-7b167472","/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"标签: 使用指南","I":0},["/tag/使用指南/"]],
  ["v-a0483a7e","/tag/%E7%8B%97%E7%8B%97/",{"y":"p","t":"标签: 狗狗","I":0},["/tag/狗狗/"]],
  ["v-655561c6","/tag/%E5%93%88%E5%A3%AB%E5%A5%87/",{"y":"p","t":"标签: 哈士奇","I":0},["/tag/哈士奇/"]],
  ["v-551ba7a4","/tag/%E8%AD%A6%E5%AF%9F/",{"y":"p","t":"标签: 警察","I":0},["/tag/警察/"]],
  ["v-b302fdee","/tag/vpn/",{"y":"p","t":"标签: vpn","I":0},[]],
  ["v-39cc843c","/tag/%E6%9C%BA%E5%9C%BA/",{"y":"p","t":"标签: 机场","I":0},["/tag/机场/"]],
  ["v-5a3e80fc","/tag/emotion/",{"y":"p","t":"标签: emotion","I":0},[]],
  ["v-49ab4c92","/tag/damage/",{"y":"p","t":"标签: damage","I":0},[]],
  ["v-0da0abf9","/tag/ai/",{"y":"p","t":"标签: ai","I":0},[]],
  ["v-2826701d","/tag/aigc/",{"y":"p","t":"标签: aigc","I":0},[]],
  ["v-63ee6e4e","/tag/stable-diffusion/",{"y":"p","t":"标签: stable diffusion","I":0},[]],
]
