export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"主页","i":"home"},["/README.md"]],
  ["v-184f4da6","/intro.html",{"y":"a","t":"介绍页","i":"circle-info"},[":md"]],
  ["v-2e3eac9e","/slides.html",{"e":"<!-- markdownlint-disable MD024 MD033 MD051 -->\n","y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-3b3841c5","/verification.html",{"e":"<p>verify_6c0c20b21d98ce1a6ba530da2971c609</p>\n","y":"a","t":""},[":md"]],
  ["v-1473bf53","/demo/",{"c":["使用指南"],"e":"<h2> 目录</h2>\n<ul>\n<li>\n<p><a href=\"/demo/markdown.html\" target=\"blank\">Markdown 展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/page.html\" target=\"blank\">页面展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/disable.html\" target=\"blank\">禁用展示</a></p>\n</li>\n<li>\n<p><a href=\"/demo/encrypt.html\" target=\"blank\">加密展示</a></p>\n</li>\n</ul>","y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"c":["使用指南"],"g":["禁用"],"e":"<p>你可以通过设置页面的 Frontmatter，在页面禁用功能与布局。</p>\n","y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"c":["使用指南"],"g":["文章加密"],"n":true,"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"c":["使用指南"],"g":["Markdown"],"e":"<p>VuePress 主要从 Markdown 文件生成页面。因此，你可以使用它轻松生成文档或博客站点。</p>\n<p>你应该创建和编写 Markdown 文件，以便 VuePress 可以根据文件结构将它们转换为不同的页面。</p>\n","y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"a":"Ms.Molingrio","d":1689120000000,"l":"2023年7月12日","c":["使用指南"],"g":["页面配置","使用指南"],"u":true,"v":"/assets/images/cover1.jpg","e":"<p><code>more</code> 注释之前的内容被视为文章摘要。</p>\n","y":"a","t":"这是一条测试","i":"file","O":1},[":md"]],
  ["v-50ec3a1f","/posts/Untitled.html",{"d":1690934400000,"l":"2023年8月2日","c":["思考"],"g":["思想","人性"],"u":true,"v":"https://i.mji.rip/2023/08/02/e34702c3c3e881603de7b58933e6c79d.jpeg","e":"<h1> 关于“思想”与“阶级”的一些思考</h1>\n<h2> 思想分支：</h2>\n<p>承认中华民族的劣根性不是自我否定。这种劣根性也不是中国所独有的。</p>\n<p>“人性本恶”论最初是由荀子提出来的。人最初的善恶是人们自我定义的，而不是客观存在的。况且同一件事情在不同人眼里有多重看法。而人之初所谓恶可没有学习过的人那版诡计多端。它所体现出的是人类原始的欲望。单纯性的想要做什么，或者讨厌什么，直接通过各种行为表现出来，不受任何拘束。</p>\n<p>于是，人们把小孩子的无拘无束，目无章法，易闯祸患的行为，通过不断的拘束和教导来规范他们在人类这个社会的适应性生活。这叫通过后天教育劝人向善。如果教育输出价值有误或者疏于教导，缺乏管束，那么人性本原的野性心理便会不断发展，在后续表现的淋漓尽致。</p>","y":"a","t":"关于“思想”与“阶级”的一些思考","O":4},[":md"]],
  ["v-7c9e35cc","/posts/husky.html",{"d":1689206400000,"l":"2023年7月13日","c":["哈士奇担任警察的可行性研究"],"g":["狗狗","哈士奇","警察"],"e":"<p>以下是关于哈士奇担任警察的可行性研究的ppt提纲：</p>\n<h1> 哈士奇担任警察的可行性研究</h1>\n<h2> 背景介绍</h2>\n<ul>\n<li>近年来，越来越多的警局开始使用犬只作为辅助工具</li>\n<li>哈士奇因其聪明、灵活、勇敢等特点备受青睐</li>\n<li>但是，哈士奇是否真的适合担任警察？需要进行可行性研究</li>\n</ul>\n<h2> 研究内容</h2>\n<ol>\n<li>哈士奇在警察工作中的优缺点分析</li>\n<li>哈士奇训练方案设计</li>\n<li>哈士奇在实际工作中的表现评估</li>\n</ol>\n<h2> 哈士奇在警察工作中的优缺点分析</h2>","y":"a","t":"哈士奇担任警察的可行性研究","i":"pen-to-square"},[":md"]],
  ["v-24b7c48d","/posts/dragonfruit.html",{"d":1689292800000,"l":"2023年7月14日","c":["vpn"],"g":["vpn","机场"],"v":"https://i.mji.rip/2023/08/02/7846b3b2eb369888e3e0f9d70336cd0d.jpeg","e":"<h1> 廉价好用机场汇总</h1>\n<h2> <a href=\"https://1.fish\" target=\"_blank\" rel=\"noopener noreferrer\">中国国际机场</a></h2>\n<p>提供试用流量   15G</p>\n<p>提供免流教程</p>\n<ul>\n<li>\n<p>一次性付款:<br>\n中杯 <strong>77.77(2048G)</strong><br>\n大杯 99.99(4096G)<br>\n超大杯 188.88(16384G)<br>\nProMax 999(114514G)</p>\n</li>\n<li>\n<p>月付<br>\n<strong>11.11(1588G)</strong></p>\n<p>22.22(3666G)<br>\n......</p>\n</li>\n</ul>","y":"a","t":"廉价好用机场汇总","i":"pen-to-square"},[":md"]],
  ["v-f0ec4556","/posts/strawberry.html",{"e":"<h1> 歌单</h1>\n<iframe frameborder=\"no\" border=\"0\" marginwidth=\"0\" marginheight=\"0\" width=\"330\" height=\"450\" src=\"//music.163.com/outchain/player?type=0&amp;id=5087813360&amp;auto=1&amp;height=430\"></iframe>\n","y":"a","t":"歌单"},[":md"]],
  ["v-df8b6e0c","/posts/tomato.html",{"d":1689552000000,"l":"2023年7月17日","c":["随笔"],"g":["emotion","damage"],"u":true,"e":"<h1> 随笔</h1>\n<figure><figcaption></figcaption></figure>\n<h2> I</h2>\n<p>无尽的阴郁将光线吞没，沉默着，却隆隆作响。</p>\n<p>人们并不清楚自己的祖先从什么时候就已经出现了，也从不追究历史长河中究竟丧失了多少人。“寿命”就如同上帝给人们戴上的枷锁，但也如同流水一般，将万物更迭。新的事物以及思想因此不断地被创造。</p>\n<p>弗莱格听闻村里面的老人说，每个人的一辈子都是上天注定的，无论历史怎样顺延，每一个前进的步伐都好像是提前写入了剧本。老人同时哀叹自身的渺小与对未来的迷茫无力。当然，弗莱格本人是不太相信这些的。他觉得很多东西可以被上天注定，唯独命运不可以。每个人应当有着创造自己命运的能力与责任。因此，他也并不是一个循规蹈矩的人。他不希望每次站在河畔，山崖边的时候，看河流永远流向一个方向，看太阳照常起落，就如同再看一遍尘封的录像带一样。</p>","y":"a","t":"随笔","i":"pen-to-square"},[":md"]],
  ["v-6408b763","/posts/elementslaw.html",{"a":"Ms.Molingrio","d":1689379200000,"l":"2023年7月15日","c":["使用指南"],"g":["ai","aigc","使用指南","stable diffusion"],"u":true,"v":"https://i.mji.rip/2023/08/02/1164afaaa1caf8ba6545568ebd42206c.jpeg","e":"<h1> 錾制元素法典 - Stable Difussion二次元通用模板</h1>\n<h2> 说明</h2>\n<p><code>Civitai&amp;社区图片常用/好用二次元parameters合集。</code></p>\n<p><code>本文中所有资料任何权益不属于整理者本人，形式上借鉴《元素法典》</code></p>\n<ul>\n<li><strong>除内容本身外，最终解释权归 錾制千秋yuno779 所有</strong></li>\n<li><strong>合集内容为二次元相关tag串合集，最好使用二次元模型而非3D</strong></li>\n<li><strong>大部分示例图为KawaICE模型生成:</strong><a href=\"https://civitai.com/models/51057/\" target=\"_blank\" rel=\"noopener noreferrer\"><strong>https://civitai.com/models/51057/</strong></a></li>\n<li><strong>本tag集会持续整理，详情链接：<a href=\"https://civitai.com/models/62473\" target=\"_blank\" rel=\"noopener noreferrer\">https://civitai.com/models/62473</a></strong></li>\n<li><strong>本parameters集不含有NSFW内容</strong></li>\n<li><strong>由于存在不良商家拿着本文去坑其小白的钱，故限制合集转载：</strong></li>\n<li><strong>《CIVITAI法典》第一发布链接：<a href=\"https://civitai.com/models/62473\" target=\"_blank\" rel=\"noopener noreferrer\">https://civitai.com/models/62473</a></strong></li>\n<li><strong>其余均为转载，[允许任何不含盈利行为的转载]</strong></li>\n<li><strong>禁止任何形式以此获取收益，遇到不良商家请直接举报！</strong></li>\n</ul>","y":"a","t":"錾制元素法典 - Stable Difussion二次元通用模板","i":"file","O":2},[":md"]],
  ["v-3ff14240","/posts/network.html",{"d":1690243200000,"l":"2023年7月25日","c":["使用指南"],"g":["network","无线","openwrt","通讯"],"u":true,"v":"https://i.mji.rip/2023/08/02/a07310689d542f5fd2225a38470bf5ec.jpeg","e":"<h1> openwrt使用总结 - 以nanopi r2s为例</h1>\n<h2> 固件问题</h2>\n<p>买的设备自带Istore os，但是有几个重要的问题。</p>\n<ol>\n<li>软重启失效，任何形式的重启操作都会死机。只能强制断电来实现手动重启</li>\n<li>运行不稳定。每次运行不超过12h后必死机。第一次发现是在早上（突然没有网络，也登不进管理页面。）</li>\n<li>正常开启了几个插件，负载通常在0.8左右，并且内存占用和缓存一直是在肉眼可见的递增状态。死机总是在不经意间~</li>\n</ol>\n<p>在经历过<strong>把lan口设置为DHCP</strong>的蠢事后，管理页面彻底进不去了，而在reset后所有插件都不见了。还好拿到手后第一时间做了<strong>备份</strong>。但是由于软重启失效的缘故，备份还原的过程相当不顺利，几乎所有的插件都无法还原。此时产生了新的bug：</p>","y":"a","t":"openwrt使用总结 - 以nanopi r2s为例","O":3},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-e1e3da16","/posts/",{"y":"p","t":"Posts"},[]],
  ["v-5bc93818","/category/",{"y":"p","t":"分类","I":0},[]],
  ["v-744d024e","/tag/",{"y":"p","t":"标签","I":0},[]],
  ["v-e52c881c","/article/",{"y":"p","t":"文章","I":0},[]],
  ["v-154dc4c4","/star/",{"y":"p","t":"收藏","I":0},[]],
  ["v-01560935","/timeline/",{"y":"p","t":"时间轴","I":0},[]],
  ["v-03d57386","/category/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"使用指南 分类","I":0},["/category/使用指南/"]],
  ["v-83e1f92e","/tag/%E7%A6%81%E7%94%A8/",{"y":"p","t":"标签: 禁用","I":0},["/tag/禁用/"]],
  ["v-4a333ee5","/category/%E6%80%9D%E8%80%83/",{"y":"p","t":"思考 分类","I":0},["/category/思考/"]],
  ["v-1e447d61","/tag/%E6%96%87%E7%AB%A0%E5%8A%A0%E5%AF%86/",{"y":"p","t":"标签: 文章加密","I":0},["/tag/文章加密/"]],
  ["v-5e7d3ae0","/category/%E5%93%88%E5%A3%AB%E5%A5%87%E6%8B%85%E4%BB%BB%E8%AD%A6%E5%AF%9F%E7%9A%84%E5%8F%AF%E8%A1%8C%E6%80%A7%E7%A0%94%E7%A9%B6/",{"y":"p","t":"哈士奇担任警察的可行性研究 分类","I":0},["/category/哈士奇担任警察的可行性研究/"]],
  ["v-484552dc","/tag/markdown/",{"y":"p","t":"标签: Markdown","I":0},[]],
  ["v-65f6c1d3","/category/vpn/",{"y":"p","t":"vpn 分类","I":0},[]],
  ["v-a378ad66","/tag/%E9%A1%B5%E9%9D%A2%E9%85%8D%E7%BD%AE/",{"y":"p","t":"标签: 页面配置","I":0},["/tag/页面配置/"]],
  ["v-60649a06","/category/%E9%9A%8F%E7%AC%94/",{"y":"p","t":"随笔 分类","I":0},["/category/随笔/"]],
  ["v-7b167472","/tag/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/",{"y":"p","t":"标签: 使用指南","I":0},["/tag/使用指南/"]],
  ["v-b6fb0184","/tag/%E6%80%9D%E6%83%B3/",{"y":"p","t":"标签: 思想","I":0},["/tag/思想/"]],
  ["v-0be1bba1","/tag/%E4%BA%BA%E6%80%A7/",{"y":"p","t":"标签: 人性","I":0},["/tag/人性/"]],
  ["v-a0483a7e","/tag/%E7%8B%97%E7%8B%97/",{"y":"p","t":"标签: 狗狗","I":0},["/tag/狗狗/"]],
  ["v-655561c6","/tag/%E5%93%88%E5%A3%AB%E5%A5%87/",{"y":"p","t":"标签: 哈士奇","I":0},["/tag/哈士奇/"]],
  ["v-551ba7a4","/tag/%E8%AD%A6%E5%AF%9F/",{"y":"p","t":"标签: 警察","I":0},["/tag/警察/"]],
  ["v-b302fdee","/tag/vpn/",{"y":"p","t":"标签: vpn","I":0},[]],
  ["v-39cc843c","/tag/%E6%9C%BA%E5%9C%BA/",{"y":"p","t":"标签: 机场","I":0},["/tag/机场/"]],
  ["v-5a3e80fc","/tag/emotion/",{"y":"p","t":"标签: emotion","I":0},[]],
  ["v-49ab4c92","/tag/damage/",{"y":"p","t":"标签: damage","I":0},[]],
  ["v-0da0abf9","/tag/ai/",{"y":"p","t":"标签: ai","I":0},[]],
  ["v-2826701d","/tag/aigc/",{"y":"p","t":"标签: aigc","I":0},[]],
  ["v-63ee6e4e","/tag/stable-diffusion/",{"y":"p","t":"标签: stable diffusion","I":0},[]],
  ["v-49627fe2","/tag/network/",{"y":"p","t":"标签: network","I":0},[]],
  ["v-40d48f2c","/tag/%E6%97%A0%E7%BA%BF/",{"y":"p","t":"标签: 无线","I":0},["/tag/无线/"]],
  ["v-6f0097ee","/tag/openwrt/",{"y":"p","t":"标签: openwrt","I":0},[]],
  ["v-9024c41e","/tag/%E9%80%9A%E8%AE%AF/",{"y":"p","t":"标签: 通讯","I":0},["/tag/通讯/"]],
]
